version: "3.2"
services:
  app:
    build: ./app
    image: ghcr.io/lacop/udrb-app:latest
    ports:
      - "2101:2101"
    depends_on:
      - chrome
    env_file:
      - path: config/.env
        required: true
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=2101
      - UDRB_OUTPUT_DIR=/output
      - UDRB_DOMAIN_CONFIG=/cfg/domains.yaml
      - UDRB_CHROME_ADDRESS=chrome:9222
      - UDRB_CHROME_KILL_ADDRESS=http://chrome:9999
      - UDRB_SLACK_MAX_AGE_SECONDS=300
    volumes:
      - type: bind
        source: ./config
        target: /cfg
        read_only: true
      - type: bind
        source: ./output
        target: /output
  chrome:
    build: ./browser
    image: ghcr.io/lacop/udrb-chrome:latest
    ports:
      - "9222:9222"
      - "9999:9999"
    restart: unless-stopped
