version: "3.2"
services:
  app:
    build: .
    ports:
      - "2101:2101"
    depends_on:
      - chrome
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=2101
      - HOSTNAME=https://udrb.lacop.dev
      - UDRB_OUTPUT=/output
      - UDRB_CONFIG=/cfg/config.toml
      - UDRB_CHROME_ADDRESS=chrome:9222
    volumes:
      - type: bind
        source: ./config
        target: /cfg
        read_only: true
      - type: bind
        source: ./output
        target: /output
  chrome:
    build: ./browser
    ports:
      - "9222:9222"
    restart: on-failure
