[package]
name = "app"
version = "0.1.0"
authors = ["lacop <lacop@lacop.net>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
failure = "0.1.5"
rust-crypto ="0.2.36"
rocket = "0.4.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_qs = "0.4.5"
reqwest = "0.9.11"
websocket = "0.22.3"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]