[package]
name = "app"
version = "0.2.0"
authors = ["lacop <lacop@lacop.net>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
constant_time_eq = "0.3"
hex = "0.4"
hmac-sha256 = "1.1"
log = "0.4"
regex = "1.10"
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_qs = "0.12"
serde_regex = "1.1"
serde_yaml = "0.9"

# base64 = "0.10.1"
# dns-lookup = "1.0.0"
# env_logger = "0.7.1"
# time = "0.1.42"
# reqwest = "0.9.11"
# url = "1.7.2"
# websocket = "0.22.3"
